[package]
name = "rustyweb"
version = "0.1.0"
authors = ["Simon Heath <icefoxen@gmail.com>"]

[dependencies]
serde_derive = "1"
serde = "1"
lazy_static = "1"
base64 = "0.10"
ring = "0.14"
untrusted = "0.6"
chrono = { version = "0.4", features = ["serde"] }


[dev-dependencies]
reqwest = "0.9"
